name: covid
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.1
  - pip=19.3.1
  - pandas=0.25.3
  - matplotlib=3.1.3
  - requests=2.23.0
  - pip:
    - streamlit==0.52.2
    - beautifulsoup4==4.9.0